### ISSUE TITLE
RuntimeError: XBMC is not playing any file

### ISSUE THREAD

**Issue by VuzzyM** [cguZZman/script.module.clouddrive.common#16]
Because of this addon, it blocks another addon, the function of another addon, please fix...

 NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.elementum/history?infohash=67678d124cf4d5fb413b11bb5bc9e879dc0c2563
2020-06-03 21:00:05.053 T:3744420672  NOTICE: Creating InputStream
2020-06-03 21:00:05.054 T:3744420672 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.elementum/history?infohash=67678d124cf4d5fb413b11bb5bc9e879dc0c2563
2020-06-03 21:00:05.055 T:3744420672   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.elementum/history?infohash=67678d124cf4d5fb413b11bb5bc9e879dc0c2563]
2020-06-03 21:00:05.055 T:3744420672  NOTICE: CVideoPlayer::OnExit()
2020-06-03 21:00:05.167 T:3752813376   ERROR: EXCEPTION: XBMC is not playing any file
2020-06-03 21:00:05.169 T:3752813376   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XBMC is not playing any file
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.clouddrive.common/clouddrive/common/service/player.py", line 74, in onPlayBackStarted
                                                Logger.debug('playback started: %s' % self.getPlayingFile())
                                            RuntimeError: XBMC is not playing any file
                                            -->End of Python script error report<--

Log - http://paste.kodi.tv/citatabezu

**Comment by cguZZman** [comment]
Thanks for reporting. Will be fixed.

**Comment by disgrace2029** [comment]
Lontron 

> Because of this addon, it blocks another addon, the function of another addon, please fix...
> 
> NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.elementum/history?infohash=67678d124cf4d5fb413b11bb5bc9e879dc0c2563
> 2020-06-03 21:00:05.053 T:3744420672 NOTICE: Creating InputStream
> 2020-06-03 21:00:05.054 T:3744420672 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.elementum/history?infohash=67678d124cf4d5fb413b11bb5bc9e879dc0c2563
> 2020-06-03 21:00:05.055 T:3744420672 ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.elementum/history?infohash=67678d124cf4d5fb413b11bb5bc9e879dc0c2563]
> 2020-06-03 21:00:05.055 T:3744420672 NOTICE: CVideoPlayer::OnExit()
> 2020-06-03 21:00:05.167 T:3752813376 ERROR: EXCEPTION: XBMC is not playing any file
> 2020-06-03 21:00:05.169 T:3752813376 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
> - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
> Error Type: <type 'exceptions.RuntimeError'>
> Error Contents: XBMC is not playing any file
> Traceback (most recent call last):
> File "/storage/.kodi/addons/script.module.clouddrive.common/clouddrive/common/service/player.py", line 74, in onPlayBackStarted
> Logger.debug('playback started: %s' % self.getPlayingFile())
> RuntimeError: XBMC is not playing any file
> -->End of Python script error report<--
> 
> Log - http://paste.kodi.tv/citatabezu

Is this the error "Cloud Drive Common Module"? If so it works on my PC but not on a Firestick loaded from OpenWizard. I've done clean Kodi Install to deleting all Dependencies after uninstalling Google Drive.

**Comment by cguZZman** [comment]
fixed in latest version
