### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by t0mtee** [cguZZman/script.module.clouddrive.common#18]
```
2021-07-15 19:37:47.874 T:7060     INFO <general>: [plugin.onedrive][service-source-request-7060]: [plugin.onedrive] [2.2.8+matrix.2]/[1.3.9+matrix.2]
                                                   
                                                   HTTP Error 400: Bad Request
                                                   
                                                   Response <Exception>: {"error":{"code":"invalidRequest","message":"Path (/LiveFolders/Films/The Lord of the Rings The Fellowship of the Ring (2001)//Extras) contains invalid leading character.","innerError":{"code":"nameContainsInvalidCharacters","date":"2021-07-15T18:37:48","request-id":"2e97a5b6-a5d3-4476-8fc6-d3221f43ec31","client-request-id":"2e97a5b6-a5d3-4476-8fc6-d3221f43ec31"}}}
                                                   
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\service\source.py", line 351, in do_GET
                                                       cached_page = self.handle_resource_request(data)
                                                     File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\service\source.py", line 310, in handle_resource_request
                                                       cached_page = self.process_path(addon_name, drive_name, path)
                                                     File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\service\source.py", line 199, in process_path
                                                       response.write(Utils.encode(self.show_folder(driveid, path)))
                                                     File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\service\source.py", line 234, in show_folder
                                                       items = self.get_folder_items(driveid, path)
                                                     File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\service\source.py", line 214, in get_folder_items
                                                       items = provider.get_folder_items(path=request_path, include_download_info=True)
                                                     File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\plugin.onedrive\resources\lib\provider\onedrive.py", line 95, in get_folder_items
                                                       files = self.get('/drives/'+self._driveid+'/' + path + '/children', parameters = self._extra_parameters)
                                                     File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\remote\oauth2.py", line 104, in get
                                                       return self.request('get', path, **kwargs)
                                                     File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\remote\oauth2.py", line 101, in request
                                                       return self.prepare_request(method, path, parameters, request_params, access_tokens, headers).request_json()
                                                     File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\remote\request.py", line 219, in request_json
                                                       return json.loads(Utils.default(self.request(), self._DEFAULT_RESPONSE))
                                                     File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\remote\request.py", line 198, in request
                                                       raise rex
                                                   clouddrive.common.exception.RequestException: HTTP Error 400: Bad Request
                                                   Root cause:
                                                   Traceback (most recent call last):
                                                     File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\remote\request.py", line 132, in request
                                                       response = urllib.request.urlopen(req)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 222, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 531, in open
                                                       response = meth(req, response)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 640, in http_response
                                                       response = self.parent.error(
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 569, in error
                                                       return self._call_chain(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 649, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 400: Bad Request
                                                   
                                                   
                                                   Request URL: https://graph.microsoft.com/v1.0/drives/c5496d580b3102a8/root:/Films/The%20Lord%20of%20the%20Rings%20The%20Fellowship%20of%20the%20Ring%20%282001%29//Extras:/children?expand=thumbnails
                                                   Request data: None
                                                   Request headers: {'authorization': '*removed*'}
                                                   Response:
                                                   
                                                   Response <Exception>: {"error":{"code":"invalidRequest","message":"Path (/LiveFolders/Films/The Lord of the Rings The Fellowship of the Ring (2001)//Extras) contains invalid leading character.","innerError":{"code":"nameContainsInvalidCharacters","date":"2021-07-15T18:37:48","request-id":"2e97a5b6-a5d3-4476-8fc6-d3221f43ec31","client-request-id":"2e97a5b6-a5d3-4476-8fc6-d3221f43ec31"}}}
```
Video crashing after loading

**Comment by cguZZman** [comment]
Can you post the complete log file and explain all the steps?

**Comment by cguZZman** [comment]
Let's track the issue with https://github.com/cguZZman/plugin.onedrive/issues/57.
